name: maven-central-search
version: 0.1.11
summary: Maven Central Search
description: |
  Use Maven Central Repository Search from your command line!

grade: stable
confinement: strict
base: core
type: app

apps:
  mcs:
    command: $SNAP/bin/mcs
    plugs:
      - network

parts:
  mcs:
    plugin: dump
    source: https://github.com/mthmulders/mcs/releases/download/v0.1.11/mcs-0.1.11-linux-x86_64.tar.gz
    source-checksum: sha256/a006147115a5051db3c57f0af510a0cc2a2c033f4e254b0bb839cd2c89d950ca
    stage-packages:
      - curl

architectures:
  - build-on: amd64
    run-on: amd64
