name: maven-central-search
version: 0.1.15
summary: Maven Central Search
description: |
  Use Maven Central Repository Search from your command line!

grade: stable
confinement: strict
base: core
type: app

apps:
  mcs:
    command: $SNAP/bin/mcs
    plugs:
      - network

parts:
  mcs:
    plugin: dump
    source: https://github.com/mthmulders/mcs/releases/download/v0.1.15/mcs-0.1.15-linux-x86_64.tar.gz
    source-checksum: sha256/fd4b3070326840e4bd8c4bda05e3fc1273f248d2fef58d934b43bcb9db4e4909
    stage-packages:
      - curl

architectures:
  - build-on: amd64
    run-on: amd64
