name: maven-central-search
version: 0.1.12
summary: Maven Central Search
description: |
  Use Maven Central Repository Search from your command line!

grade: stable
confinement: strict
base: core
type: app

apps:
  mcs:
    command: $SNAP/bin/mcs
    plugs:
      - network

parts:
  mcs:
    plugin: dump
    source: https://github.com/mthmulders/mcs/releases/download/v0.1.12/mcs-0.1.12-linux-x86_64.tar.gz
    source-checksum: sha256/305106d982dfec7ceb1d8351c1dde85f060f9ea326b8d2278cd013b78ceea2f1
    stage-packages:
      - curl

architectures:
  - build-on: amd64
    run-on: amd64
