name: maven-central-search
version: 0.1.14
summary: Maven Central Search
description: |
  Use Maven Central Repository Search from your command line!

grade: stable
confinement: strict
base: core
type: app

apps:
  mcs:
    command: $SNAP/bin/mcs
    plugs:
      - network

parts:
  mcs:
    plugin: dump
    source: https://github.com/mthmulders/mcs/releases/download/v0.1.14/mcs-0.1.14-linux-x86_64.tar.gz
    source-checksum: sha256/ee7d3abf4d8b56a8c1b6848cc212fbd8469b21dbf700e2846f60096f49fd69b6
    stage-packages:
      - curl

architectures:
  - build-on: amd64
    run-on: amd64
